/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/vidya-ranganathan/mcluster/pkg/apis/cumulonimbus.ai/v1alpha1"
	cumulonimbusaiv1alpha1 "github.com/vidya-ranganathan/mcluster/pkg/client/applyconfiguration/cumulonimbus.ai/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMclusters implements MclusterInterface
type FakeMclusters struct {
	Fake *FakeCumulonimbusV1alpha1
	ns   string
}

var mclustersResource = v1alpha1.SchemeGroupVersion.WithResource("mclusters")

var mclustersKind = v1alpha1.SchemeGroupVersion.WithKind("Mcluster")

// Get takes name of the mcluster, and returns the corresponding mcluster object, and an error if there is any.
func (c *FakeMclusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Mcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mclustersResource, c.ns, name), &v1alpha1.Mcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mcluster), err
}

// List takes label and field selectors, and returns the list of Mclusters that match those selectors.
func (c *FakeMclusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MclusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mclustersResource, mclustersKind, c.ns, opts), &v1alpha1.MclusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MclusterList{ListMeta: obj.(*v1alpha1.MclusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.MclusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mclusters.
func (c *FakeMclusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mclustersResource, c.ns, opts))

}

// Create takes the representation of a mcluster and creates it.  Returns the server's representation of the mcluster, and an error, if there is any.
func (c *FakeMclusters) Create(ctx context.Context, mcluster *v1alpha1.Mcluster, opts v1.CreateOptions) (result *v1alpha1.Mcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mclustersResource, c.ns, mcluster), &v1alpha1.Mcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mcluster), err
}

// Update takes the representation of a mcluster and updates it. Returns the server's representation of the mcluster, and an error, if there is any.
func (c *FakeMclusters) Update(ctx context.Context, mcluster *v1alpha1.Mcluster, opts v1.UpdateOptions) (result *v1alpha1.Mcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mclustersResource, c.ns, mcluster), &v1alpha1.Mcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mcluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMclusters) UpdateStatus(ctx context.Context, mcluster *v1alpha1.Mcluster, opts v1.UpdateOptions) (*v1alpha1.Mcluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mclustersResource, "status", c.ns, mcluster), &v1alpha1.Mcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mcluster), err
}

// Delete takes name of the mcluster and deletes it. Returns an error if one occurs.
func (c *FakeMclusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(mclustersResource, c.ns, name, opts), &v1alpha1.Mcluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMclusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MclusterList{})
	return err
}

// Patch applies the patch and returns the patched mcluster.
func (c *FakeMclusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Mcluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.Mcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mcluster), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied mcluster.
func (c *FakeMclusters) Apply(ctx context.Context, mcluster *cumulonimbusaiv1alpha1.MclusterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Mcluster, err error) {
	if mcluster == nil {
		return nil, fmt.Errorf("mcluster provided to Apply must not be nil")
	}
	data, err := json.Marshal(mcluster)
	if err != nil {
		return nil, err
	}
	name := mcluster.Name
	if name == nil {
		return nil, fmt.Errorf("mcluster.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mclustersResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.Mcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mcluster), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeMclusters) ApplyStatus(ctx context.Context, mcluster *cumulonimbusaiv1alpha1.MclusterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Mcluster, err error) {
	if mcluster == nil {
		return nil, fmt.Errorf("mcluster provided to Apply must not be nil")
	}
	data, err := json.Marshal(mcluster)
	if err != nil {
		return nil, err
	}
	name := mcluster.Name
	if name == nil {
		return nil, fmt.Errorf("mcluster.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mclustersResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.Mcluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Mcluster), err
}
