/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	cumulonimbusaiv1alpha1 "github.com/vidya-ranganathan/mcluster/pkg/apis/cumulonimbus.ai/v1alpha1"
	versioned "github.com/vidya-ranganathan/mcluster/pkg/client/clientset/versioned"
	internalinterfaces "github.com/vidya-ranganathan/mcluster/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/vidya-ranganathan/mcluster/pkg/client/listers/cumulonimbus.ai/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MclusterInformer provides access to a shared informer and lister for
// Mclusters.
type MclusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MclusterLister
}

type mclusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMclusterInformer constructs a new informer for Mcluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMclusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMclusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMclusterInformer constructs a new informer for Mcluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMclusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CumulonimbusV1alpha1().Mclusters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CumulonimbusV1alpha1().Mclusters(namespace).Watch(context.TODO(), options)
			},
		},
		&cumulonimbusaiv1alpha1.Mcluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *mclusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMclusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *mclusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cumulonimbusaiv1alpha1.Mcluster{}, f.defaultInformer)
}

func (f *mclusterInformer) Lister() v1alpha1.MclusterLister {
	return v1alpha1.NewMclusterLister(f.Informer().GetIndexer())
}
